### ISSUE TITLE
Help me improve the colors.

### ISSUE THREAD

**Issue by OAtulA** [OAtulA/React-REDUX-TO-DO-App#3]
# Can someone suggest me a better color theme

I need help here.  
`src/components/todo.css`  

I want the bg to change for `.todo` and `.DONE`

Also kindly write the message

**Comment by OAtulA** [comment]
Also in you PR message/comment write 
`
issue #3 solved. 
`

You might add a few more lines if you wish.
As good practise.

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by OAtulA** [comment]
Go ahead mate.
It's open.

**Comment by OAtulA** [comment]
Go ahead mate.
It's open.
